### ISSUE TITLE
THIS SCRIPT IS A STEALER DO NOT RUN IT

### ISSUE THREAD

**Issue by IzTheBenjingly** [justDarian/krunker-central-cracked#2]
Bro thinks he can add stealer to open source script lol. In line 1423, the script downloads "https://raw.githubusercontent.com/justDarian/krunker-cheat/main/game_1_4.js" and if you look at the content of the url you will notice its all obfuscated. If u ran this script you most likely got ratted.

**Comment by justDarian** [comment]
your fucking retarded, game_1_4.js is a modified version of the OFFICIAL game client. it was created to expose hidden objects/functions into the global scope.

plus, my code very OBVIOUSLY clears your session token, so even if it was a syealer, i wouldnt be stealing shit 💀 
maybe do some research before talking shit about me and my work, Benjingly

**Comment by IzTheBenjingly** [comment]
lmao if its the official game client why obfuscate it? That doesnt make any sense

**Comment by justDarian** [comment]
> lmao if its the official game client why obfuscate it? That doesnt make any sense

because i dont want little skids like your ass to be stealing my shit like the retards you are? is that so hard for your dumbass to comprehend? again, do some research before you say this, there is NO way my code is a stealer 💀 
plus, maybe try deobfuscatign and doing more research before asuming that the fact some code is obfuscated means its a rat

**Comment by IzTheBenjingly** [comment]
Ah yes, my man doesnt want ppl to steal an open source script that he cracked and stole from another dude. Like you really think ppl tryna steal ur script? Lol

**Comment by justDarian** [comment]
> Ah yes, my man doesnt want ppl to steal an open source script that he cracked and stole from another dude. Like you really think ppl tryna steal ur script? Lol

people have stolen my script you dumb fuck, your actually retarded, just deobfuscate the code and see for yourself, gathering attention over nothing is a pussy move lil bro

**Comment by IzTheBenjingly** [comment]
If you turned on ur brain for one sec you would know that you cant deobfuscate this script because it has a syntax error, hence you cant see the code, hence ur hiding some shit hence its most likely a stealer.

**Comment by justDarian** [comment]
> If you turned on ur brain for one sec you would know that you cant deobfuscate this script because it has a syntax error, hence you cant see the code, hence ur hiding some shit hence its most likely a stealer. 

bro is assuming anything is a stealer skull fucking retard

**Comment by IzTheBenjingly** [comment]
Lmao ur defense to the fact that ur cracked open source script has obfuscated code is "BrO iS AsSumInG AnyThiNg Is A sTeaLeR"? do you even know what obfuscated code is? How can someone tell if a tampermonkey script is safe if its obfuscated? Also obfuscating does NOT help with ppl stealing ur script dumb faggot.

**Comment by justDarian** [comment]
> Lmao ur defense to the fact that ur cracked open source script has obfuscated code is "BrO iS AsSumInG AnyThiNg Is A sTeaLeR"? do you even know what obfuscated code is? How can someone tell if a tampermonkey script is safe if its obfuscated? Also obfuscating does NOT help with ppl stealing ur script dumb faggot.

your a dumbass
it only runs on krunker, and it doesnt have http request permission.
please, explain to me how the javascript environment can access an external server to send your ibformation
